### ISSUE TITLE
Evaluate if the current tests are sufficient / accurate for addressing the following normative statements in the spec

### ISSUE THREAD

**Issue by JSAssassin** [w3c/vc-di-ecdsa-test-suite#16]
**ecdsa-rdfc-2019:**

1. The value of the `proofValue` property of the proof **MUST** be an ECDSA signature produced according to [FIPS-186-5] and **SHOULD** use the **deterministic** ECDSA signature variant.
   - See - https://www.w3.org/TR/vc-di-ecdsa/#dataintegrityproof
   - Test - https://github.com/w3c/vc-di-ecdsa-test-suite/blob/main/tests/10-create.js#L111-L130

2. If `options.type` is not set to the string `DataIntegrityProof` and `options.cryptosuite` is not set to the string `ecdsa-rdfc-2019`, then a **PROOF_TRANSFORMATION_ERROR** **MUST** be raised.
   - See - https://www.w3.org/TR/vc-di-ecdsa/#transformation-ecdsa-rdfc-2019
   - Tests:
     - https://github.com/w3c-ccg/data-integrity-test-suite-assertion/blob/main/index.js#L299-L311
     - https://github.com/w3c/vc-di-ecdsa-test-suite/blob/update-tests/tests/20-verify.js#L53-L58

3. Set `proofConfig.created` to `options.created`. If the value is not a valid [XMLSCHEMA11-2] datetime, an **INVALID_PROOF_DATETIME** error **MUST** be raised.
   - See - https://www.w3.org/TR/vc-di-ecdsa/#transformation-ecdsa-rdfc-2019
   - Test - https://github.com/w3c-ccg/data-integrity-test-suite-assertion/blob/main/index.js#L366-L373

If the tests are inadequate and do not cover the normative statements, please provide suggestions for how we can effectively test them. @aljones15 @BigBlueHat cc: @dlongley

**Comment by BigBlueHat** [comment]
Synchronizing the tests and the specs has continued, so these should be addressed now.
