### ISSUE TITLE
ECDSA-SD-2023 proofValue encoding is base64url no padding

### ISSUE THREAD

**Issue by filip26** [w3c/vc-di-ecdsa-test-suite#41]
A test on [proofValue encoding](https://w3c.github.io/vc-di-ecdsa-test-suite/#Data%20Integrity%20(ecdsa-sd-2023%20issuers)) requires proofValue be encoded with `base58btc` for ecdsa-sd-2013, but the spec asks for `base64url` no padding. 

There is an inconsistency in the spec, (see https://github.com/w3c/vc-di-ecdsa/issues/55) asking `base58btc` generally but then requiring `base64url` no padding only for `ecdsa-sd-2013`

**Comment by tminard** [comment]
@filip26 I think you meant ecdsa-sd-2023?

I just merged a fix to [data-integrity-test-suite-assertion](https://github.com/w3c-ccg/data-integrity-test-suite-assertion/pull/28) that resolves this.

**Comment by filip26** [comment]
@tminard yes I did, ECDSA-SD-2023

**Comment by tminard** [comment]
Awesome - thanks @filip26! Makes sense. Are you able to re-run the test and see if this is still an issue? I believe we can close this now.

I verified with folks that the spec is currently correct: specific cryptosuites have normative statements around the specific multibase encoding expected for `proof.proofValue`. The test suites now account for this.

**Comment by aljones15** [comment]
@tminard @filip26 closing as I believe this has been addressed
